name: decision_dungeon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/fonts/
    - assets/images/scene/start/
    - assets/images/scene/ghoul/
    - assets/images/scene/chest/
    - assets/images/scene/altar/
    - assets/images/scene/victory/
    - assets/images/scene/cursed/
    - assets/images/scene/escape/
    - assets/images/scene/game_over/
    - assets/images/scene/library/
    - assets/images/scene/altar_flame/
    - assets/images/scene/relic_vault/
    

  fonts:
    - family: Jacquard12
      fonts:
        - asset: assets/fonts/Jacquard12-Regular.ttf

    - family: Kings
      fonts:
        - asset: assets/fonts/Kings-Regular.ttf

    - family: MedievalSharp
      fonts:
        - asset: assets/fonts/MedievalSharp-Regular.ttf
